# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awarded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('nit', models.CharField(max_length=12)),
                ('department', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('nog', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=40)),
                ('modality', models.CharField(max_length=100)),
                ('competition_type', models.CharField(max_length=70)),
                ('purchasing_unit', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('publication_date', models.DateTimeField(verbose_name='fecha de publicación')),
                ('presentation_date', models.DateTimeField(null=True, verbose_name='fecha de presentación de ofertas')),
                ('close_date', models.DateTimeField(verbose_name='Fecha de cierre')),
                ('reception_type', models.CharField(max_length=125)),
                ('end_date', models.DateTimeField(verbose_name='Fecha de finalización')),
                ('categories', models.ManyToManyField(to='GCEstadisticas.PurchaseCategory')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GCEstadisticas.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lprv', models.IntegerField(verbose_name='id proveedor en guatecompras')),
                ('nit', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GCEstadisticas.Requisition'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GCEstadisticas.Supplier'),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GCEstadisticas.EntityType'),
        ),
        migrations.AddField(
            model_name='awarded',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GCEstadisticas.Requisition'),
        ),
        migrations.AddField(
            model_name='awarded',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GCEstadisticas.Supplier'),
        ),
    ]
