# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCEstadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='lprv',
            field=models.IntegerField(null=True, verbose_name='id proveedor en guatecompras'),
        ),
    ]
