# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCEstadisticas', '0003_auto_20161206_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='nit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
